Repository livekit/protocol, pull requests merged in 2025-09, with the labels that each got.

#1199 Replay updates
  .github/workflows/slack-notifier.yaml
  protobufs/cloud_replay.proto
  replay/cloud_replay.pb.go
  replay/cloud_replay.twirp.go
Labels: slack-ts:cs-devs:1757365013.933419

#1197 add recording store request header
  auth/grants.go
  livekit/livekit_metrics.pb.go
  protobufs/livekit_metrics.proto
  utils/guid/id.go
  utils/guid/id_test.go
Labels: slack-ts:cs-devs:1757996513.702269

#1214 add observability grant setter
  .changeset/four-jokes-build.md
  auth/accesstoken.go
Labels: slack-ts:cs-devs:1758070272.467159

#1232 Making the sip refer to compliant to the RFC
  livekit/sip.go
  livekit/sip_test.go
Labels: slack-ts:telephony-devs:1759144468.076379

#1230 update api
  protobufs/cloud_replay.proto
  replay/cloud_replay.pb.go
  replay/cloud_replay.twirp.go
Labels: slack-ts:cs-devs:1758910201.811779

#1234 Set IsClusterMode When ClusterAddresses is used
  redis/redis.go
Labels: slack-ts:cs-devs:1759202726.652509
